# Linear Algebra

In [1]:
import math
import random
import numpy as np
import matplotlib.pyplot as plt


In [3]:
v1= np.array([1,2,3])
v2= np.array([4,5,6])

In [4]:
print (v1)
print(v2)

[1 2 3]
[4 5 6]


In [6]:
v_add = v1+v2
v_sub = v1-v2

print(v_add)
print (v_sub)

[5 7 9]
[-3 -3 -3]


In [7]:
scalar = 2
v_scaled = scalar * v1
print(v_scaled)

[2 4 6]


In [8]:
dot_product = np.dot(v1, v2)
print (dot_product)

32


In [9]:
magnitude = np.linalg.norm(v1 #squared root of the sum of the squared components
print(magnitude)

3.7416573867739413


In [11]:
#Creting matrix
A = np.array([[1,2,3], [4,5,6]]) #2x3
print (A)
print()

B=np.array ([[7,8,9], [10,11, 12], [13,14,15]]) #3x3
print (B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [14]:
C = np.array([[1,2,3], [4,5,6]])
matrix_add = A+C
matrix_sub = A-C

print("A+C=\n", matrix_add)
print("A-C", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C [[0 0 0]
 [0 0 0]]


In [15]:
matrix_mul = np.dot(A,B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [16]:
#transpose
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
#Ax = b  A id A is the coefficient matrix,x is the vector of unknowns, b is the constant vector
#2x +3y = 5
#4x -1y = 3

#Coefficient matrix A and constant vector b

A = np.array([[2,3], [4,-1]])
b = np.array([5,3])
print("A = ",A)
print("b =", b)

#Solving for A * x = b
x=np.linalg.solve(A, b)
print("solution = ",x)

A =  [[ 2  3]
 [ 4 -1]]
b = [5 3]
solution =  [1. 1.]


In [22]:
E = np.array([[1,2], [2,1]]A
eigenvalues, eigenvectors = np.linalg.eig(E)
print("Eigenvalues = ",eigenvalues)
print("eigenvectors = ", eigenvectors)

Eigenvalues =  [ 3. -1.]
eigenvectors =  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [26]:
#Inverse
A= np.array([[4,7], [2,6]])
A_inv = np.linalg.inv(A)
print(A)
print("Inverse of matrix A = ", A_inv)




[[4 7]
 [2 6]]
Inverse of matrix A =  [[ 0.6 -0.7]
 [-0.2  0.4]]


In [28]:
identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


## Singular Value Decomposition (SVD) is a factorization of a matrix into three matrices:
## A=UΣV T
## Where:
## ● U and V are orthogonal matrices,
## ● Σ is a diagonal matrix of singular values.

In [29]:
#Singular Value Decomposition
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
# Perform SVD
U, sigma, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
